### ISSUE TITLE
Update readme with runnable example

### ISSUE THREAD

**Issue by waynethewizard** [norman784/gaiku#1]
It looks like there are 3d examples one could run but no explanation for how to do so. It'd be great to get these running and add some direction and pictures. Thanks!

**Comment by norman784** [comment]
The examples right now only transform from png/goxel to a normalized format and then export to `.obj` files, as requested I updated the Readme with some instructions and screenshots, I didn't wanted to do it, because there are issues with the marching cube algorithm and it leave spaces between chunks, is a know issue but I didn't solve it yet, still I need to find more time to spend on this project but it might not be this year.

Thanks for showing interest in the project, feel free to contibute or ask questions.

**Comment by waynethewizard** [comment]
Yes, it's definitely a problem that I want to help solve and will be actively working on. I'll see about contributing to what you have here. Thank you!
