### ISSUE TITLE
Gox files doesn't appear to have the correct orientation.

### ISSUE THREAD

**Issue by norman784** [norman784/gaiku#28]
There's an issue that I spotted from the beginning but never bother to fix, and it's that all gox files are rotated, so right now they need a monkey patch to show correctly in the game engines or when exporting.

**Comment by QuantumEntangledAndy** [comment]
This is game engine dependant. For example the coordinate system could be

- left handed z-up
- right handed z-up
- left handed y-up
- right handed yup

I belive that gox is left-handed zup while amethyst is left handed y-up which is why the rotation is needed. Fyi if they were left zup and right yup we would convert by swapping the z and y axes instead of rotating.

We need to decide what the coordinat system of gaiku is. Anything that is imported should be converted to this internal format and then when exported it should be converted into the target one.

**Comment by norman784** [comment]
> I belive that gox is left-handed zup

Thanks @QuantumEntangledAndy it is obvious if you know what could be the cause, I was not aware about that.

> ...amethyst is left handed y-up which is why the rotation is needed.
> We need to decide what the coordinat system of gaiku is.

I think we should support what's used by amethyst and/or bevy, I could only checked in bevy the #33 fix, and the model is correctly shown.
